import { EmbedBuilder, SlashCommandBuilder } from "discord.js";
const answers = [
    // Réponses positives
    "C'est certain.",
    "C'est le cas.",
    "Sans aucun doute.",
    "Définitivement, Oui.",
    "Tu peux compter dessus.",
    "Comme je le vois, oui.",
    "Très probablement.",
    "Les perspectives sont bonnes.",
    "Oui.",
    "Tout porte à croire que oui.",
    "Oui absolument.",
    "C'est bien parti",
    "C'est ton destin.",
    "Évidemment !",
    "Ça c'est sûr !",
    "100% garanti !",
    "Bien sûr que oui !",
    "Tu as tout compris !",
    "Exactement !",
    "Tu peux y aller les yeux fermés !",
    "C'est du tout cuit !",
    "Fais-toi plaisir !",
    "Go for it !",
    "Carpe diem !",
    "Fonce !",
    "N'hésite pas !",
    "Lance-toi !",
    
    // Réponses neutres/floues
    "Réponse floue, essayez à nouveau.",
    "Repose ta question plus tard.",
    "Il vaut mieux ne pas te le dire maintenant.",
    "Impossible de prédire maintenant.",
    "Concentrez-vous et demandez à nouveau.",
    "Pas d'avis.",
    "Je ne suis pas sûr.",
    "Peut-être... ou pas.",
    "Ça dépend de toi.",
    "Les astres sont flous aujourd'hui.",
    "Demande à ta mère.",
    "Je ne sais pas, je ne suis qu'une boule magique.",
    "Pose-moi la question demain.",
    "Les esprits sont en vacances.",
    "Je réfléchis encore...",
    "La réponse est dans ton cœur.",
    "C'est compliqué...",
    "50/50, pile ou face !",
    "Mystère et boule de gomme.",
    "Ça reste à voir.",
    "On verra bien.",
    "Sais pas, sais pas...",
    "Euh... passe ton tour.",
    
    // Réponses négatives
    "N'y comptez pas.",
    "Ma réponse est non.",
    "Mes sources me disent que non.",
    "Les perspectives ne sont pas très bonnes.",
    "Très douteux.",
    "Non.",
    "Certainement pas.",
    "Pas du tout.",
    "Niet.",
    "Faut pas rêver",
    "Dans tes rêves !",
    "Tu peux toujours courir !",
    "Même pas en rêve !",
    "Non mais allo quoi !",
    "Tu plaisantes j'espère ?",
    "Absolument pas !",
    "Jamais de la vie !",
    "Oublie ça tout de suite !",
    "Nan mais sérieusement ?",
    "Tu peux oublier ça !",
    "Niet kopeck !",
    "Nada !",
    "Que dalle !",
    "Peau de balle !",
    "Walou !",
    
    // Réponses drôles/décalées
    "Ta gueule, fils de pute !!!",
    "Demande à Siri, elle est plus maligne.",
    "J'ai pas envie de répondre.",
    "Ça va pas la tête ?",
    "Tu me prends pour qui ?",
    "Mdr, non.",
    "Hahaha... NON.",
    "Tu rigoles ou quoi ?",
    "Même mon chat sait mieux que ça.",
    "J'ai la flemme de calculer.",
    "Error 404: réponse not found.",
    "Je suis en panne aujourd'hui.",
    "Essaie de débrancher et rebrancher ta question.",
    "Ma batterie est faible, repose la question.",
    "Je suis occupé à regarder Netflix.",
    "Demande à Google, moi je suis en pause.",
    "Je ne suis pas payé assez pour ça.",
    "Tu veux que je fasse un dessin ?",
    "C'est au-dessus de mes compétences.",
    "Mon syndicat m'interdit de répondre.",
    "Je suis en RTT aujourd'hui.",
    "Contactez mon manager.",
    "Je ne réponds qu'aux VIP.",
    "Tu n'as pas le niveau requis.",
    "Accès refusé !",
    "Réessaie avec un svp au moins.",
    "Tu m'as dit bonjour au moins ?",
    "Je suis fermé pour inventaire.",
    "Service temporairement indisponible.",
    "Veuillez patienter, votre appel est important.",
    "Toutes nos lignes sont occupées.",
    "Raccrochez et rappelez.",
    "Ce service coûte 3€ par minute.",
    "Vous n'avez pas les autorisations nécessaires.",
    "Achetez la version premium pour débloquer cette réponse.",
    "Contenu réservé aux abonnés.",
    "Désolé, j'ai oublié ma boule de cristal.",
    "Ma connexion Wi-Fi est pourrie.",
    "Je suis en mode avion.",
    "Erreur de connexion au serveur.",
    "Timeout : temps de réponse dépassé.",
    "Je dois demander à mon avocat d'abord.",
    "Cette information est classée secrète.",
    "Je plaide le 5ème amendement.",
    "No comment.",
    "Je ne confirme ni n'infirme.",
    "Sources : fais-moi confiance frère.",
    "C'est compliqué, tu comprendrais pas.",
    "J'ai signé un NDA, je peux pas dire.",
    "Mon algorithme a planté.",
    "Réponse en cours de téléchargement... 99%",
    "Mise à jour requise pour cette fonctionnalité.",
    "Tu as dépassé ton quota de questions.",
    "Version d'essai expirée.",
    "Fonctionnalité non disponible dans ta région.",
    "Contenu bloqué par le contrôle parental.",
    "Je suis en cours de maintenance.",
    "Serveur surchargé, réessayez plus tard.",
    "Ta question viole nos conditions d'utilisation.",
    "Contenu signalé comme spam.",
    "Je suis une IA, pas un oracle !",
    "Désolé, je ne parle que le binaire.",
    "01001110 01001111 01001110 (Non en binaire).",
    "Calcul en cours... veuillez patienter 3 jours.",
    "Ma base de données est corrompue.",
    "Je ne réponds qu'aux questions intelligentes.",
    "Erreur : division par zéro détectée.",
    "Stackoverflow exception.",
    "Null pointer exception.",
    "Segmentation fault.",
    "Blue screen of death.",
    "Je dois redémarrer, brb.",
    "Antivirus a bloqué ma réponse.",
    "Firewall a filtré ta question.",
    "Je suis en quarantaine.",
    "Social distancing avec ta question.",
    "Je porte un masque, tu m'entends pas bien.",
    "Je suis vacciné contre les questions nulles.",
    "Test PCR négatif pour les bonnes réponses.",
    "Je suis en télétravail depuis chez moi.",
    "Visioconférence annulée.",
    "Mon micro est coupé.",
    "Tu es en mute.",
    "Connexion instable.",
    "Tu coupes, je t'entends mal.",
    "On se rappelle ?",
    "J'ai un autre appel.",
    "Ma batterie va mourir.",
    "Plus de réseau.",
    "Zone blanche détectée.",
    "Roaming désactivé.",
    "Je suis sur répondeur.",
    "Laissez un message après le bip.",
    "Vous êtes en file d'attente, position 42.",
    "Appuyez sur 1 pour continuer.",
    "Pour parler à un conseiller, appuyez sur #.",
    "Menu vocal indisponible.",
    "Je ne prends que les RDV sur Doctolib.",
    "Complet jusqu'en 2025.",
    "Liste d'attente fermée.",
    "Inscription obligatoire.",
    "Présentation d'un pass sanitaire requise.",
    "QR code invalide.",
    "Votre compte a été suspendu.",
    "Mot de passe incorrect.",
    "Trop de tentatives, réessayez dans 24h.",
    "Session expirée.",
    "Cookies requis.",
    "Veuillez accepter les CGU.",
    "RGPD, toussa toussa...",
    "J'ai pas consenti au traitement de ta question.",
    "Formulaire de contact indisponible.",
    "Boîte mail pleine.",
    "Message non délivré.",
    "Adresse introuvable.",
    "Destinataire inconnu au bataillon.",
    "Facteur en grève.",
    "Courrier perdu par La Poste.",
    "Livraison impossible, personne au domicile.",
    "Avis de passage déposé.",
    "Colis en instance.",
    "Douanes françaises, votre colis est bloqué.",
    "Taxe de 15€ à payer pour débloquer.",
    "Lien suspect, ne cliquez pas.",
    "Phishing détecté !",
    "Arnaque signalée aux autorités.",
    "FBI, open up !",
    "Police, ne bougez plus !",
    "Vous avez le droit de garder le silence.",
    "Tout ce que vous direz pourra être retenu contre vous.",
    "Un avocat peut vous être commis d'office.",
    "Vous êtes en état d'arrestation.",
    "Menottes, fouille au corps.",
    "Cellule de dégrisement.",
    "Amende de 135€.",
    "Retrait de permis.",
    "Contrôle technique défavorable.",
    "Assurance résiliée.",
    "Interdiction bancaire.",
    "Fichage Banque de France.",
    "Huissier à domicile.",
    "Saisie sur salaire.",
    "Expulsion locative.",
    "Homeless en approche..."
];

export const command = {
    data: new SlashCommandBuilder()
        .setName("8ball")
        .setDescription("Je répond à vos questions")
        .addStringOption((option) =>
            option
                .setName("question")
                .setDescription("Écris ta question")
                .setRequired(true)
        ),

    async execute(message) {
        try {
            const question = message.options.getString("question");

            const embed = new EmbedBuilder()
                .setTitle("🎱  The Magic 8-Ball  🎱")
                //.setDescription("**-----------------------------**")
                .addFields({name: "Question", value: `\`${question}\``},
                {
                    name: "Réponse",
                    value: `\`${answers[Math.floor(Math.random() * answers.length)]}\``
                })
                .setTimestamp()
                .setColor("#6f00ff");

            await message.reply({ embeds: [embed] });
        } catch (error) {
            console.error("❌ Une erreur s'est produite dans la commande '8ball' :", error);
            await message.reply({
                embeds: [
                    {
                        description: "❌ Une erreur inattendue s'est produite. Veuillez réessayer plus tard.",
                        color: 0xff0000,
                    },
                ],
            });
        }
    },
};
